---
- hosts: all
  become: true
  vars_files:
    - config.yaml
  roles:
    - base

- hosts: db_servers
  become: true
  vars_files:
    - config.yaml
  roles:
    - mariadb

- hosts: monitoring_servers
  become: true
  vars_files:
    - config.yaml
  roles:
    - nagios

- hosts: all
  become: true
  vars_files:
    - config.yaml
  roles:
    - motd
